from __future__ import annotations

from typing import Any

from ADSMOD.server.utils.constants import (
    COLUMN_AIC,
    COLUMN_AICC,
    COLUMN_OPTIMIZATION_METHOD,
    COLUMN_SCORE,
)

###############################################################################
MODEL_SCHEMAS: dict[str, dict[str, Any]] = {
    "LANGMUIR": {
        "prefix": "Langmuir",
        "table": "ADSORPTION_LANGMUIR",
        "fields": {
            "optimization_method": COLUMN_OPTIMIZATION_METHOD,
            "score": COLUMN_SCORE,
            "k": "k",
            "k_error": "k error",
            "qsat": "qsat",
            "qsat_error": "qsat error",
            "aic": COLUMN_AIC,
            "aicc": COLUMN_AICC,
        },
    },
    "SIPS": {
        "prefix": "Sips",
        "table": "ADSORPTION_SIPS",
        "fields": {
            "optimization_method": COLUMN_OPTIMIZATION_METHOD,
            "score": COLUMN_SCORE,
            "k": "k",
            "k_error": "k error",
            "qsat": "qsat",
            "qsat_error": "qsat error",
            "exponent": "exponent",
            "exponent_error": "exponent error",
            "aic": COLUMN_AIC,
            "aicc": COLUMN_AICC,
        },
    },
    "FREUNDLICH": {
        "prefix": "Freundlich",
        "table": "ADSORPTION_FREUNDLICH",
        "fields": {
            "optimization_method": COLUMN_OPTIMIZATION_METHOD,
            "score": COLUMN_SCORE,
            "k": "k",
            "k_error": "k error",
            "exponent": "exponent",
            "exponent_error": "exponent error",
            "aic": COLUMN_AIC,
            "aicc": COLUMN_AICC,
        },
    },
    "TEMKIN": {
        "prefix": "Temkin",
        "table": "ADSORPTION_TEMKIN",
        "fields": {
            "optimization_method": COLUMN_OPTIMIZATION_METHOD,
            "score": COLUMN_SCORE,
            "k": "k",
            "k_error": "k error",
            "beta": "beta",
            "beta_error": "beta error",
            "aic": COLUMN_AIC,
            "aicc": COLUMN_AICC,
        },
    },
    "TOTH": {
        "prefix": "Toth",
        "table": "ADSORPTION_TOTH",
        "fields": {
            "optimization_method": COLUMN_OPTIMIZATION_METHOD,
            "score": COLUMN_SCORE,
            "k": "k",
            "k_error": "k error",
            "qsat": "qsat",
            "qsat_error": "qsat error",
            "exponent": "exponent",
            "exponent_error": "exponent error",
            "aic": COLUMN_AIC,
            "aicc": COLUMN_AICC,
        },
    },
    "DUBININ_RADUSHKEVICH": {
        "prefix": "Dubinin-Radushkevich",
        "table": "ADSORPTION_DUBININ_RADUSHKEVICH",
        "fields": {
            "optimization_method": COLUMN_OPTIMIZATION_METHOD,
            "score": COLUMN_SCORE,
            "qsat": "qsat",
            "qsat_error": "qsat error",
            "beta": "beta",
            "beta_error": "beta error",
            "aic": COLUMN_AIC,
            "aicc": COLUMN_AICC,
        },
    },
    "DUAL_SITE_LANGMUIR": {
        "prefix": "Dual-Site Langmuir",
        "table": "ADSORPTION_DUAL_SITE_LANGMUIR",
        "fields": {
            "optimization_method": COLUMN_OPTIMIZATION_METHOD,
            "score": COLUMN_SCORE,
            "k1": "k1",
            "k1_error": "k1 error",
            "qsat1": "qsat1",
            "qsat1_error": "qsat1 error",
            "k2": "k2",
            "k2_error": "k2 error",
            "qsat2": "qsat2",
            "qsat2_error": "qsat2 error",
            "aic": COLUMN_AIC,
            "aicc": COLUMN_AICC,
        },
    },
    "REDLICH_PETERSON": {
        "prefix": "Redlich-Peterson",
        "table": "ADSORPTION_REDLICH_PETERSON",
        "fields": {
            "optimization_method": COLUMN_OPTIMIZATION_METHOD,
            "score": COLUMN_SCORE,
            "k": "k",
            "k_error": "k error",
            "a": "a",
            "a_error": "a error",
            "beta": "beta",
            "beta_error": "beta error",
            "aic": COLUMN_AIC,
            "aicc": COLUMN_AICC,
        },
    },
    "JOVANOVIC": {
        "prefix": "Jovanovic",
        "table": "ADSORPTION_JOVANOVIC",
        "fields": {
            "optimization_method": COLUMN_OPTIMIZATION_METHOD,
            "score": COLUMN_SCORE,
            "k": "k",
            "k_error": "k error",
            "qsat": "qsat",
            "qsat_error": "qsat error",
            "aic": COLUMN_AIC,
            "aicc": COLUMN_AICC,
        },
    },
}
