[project]
name = "adsmod-ml"
version = "3.0.0"
requires-python = ">=3.14"
dependencies = [
    "adsmod-common",
    "adsmod-core",
    "fastapi==0.128.0",
    "torch==2.10.0+cu130",
    "keras==3.13.1",
    "scikit-learn==1.8.0",
    "numpy==2.5.2",
    "pandas==3.0.5"
]

[tool.uv.sources]
adsmod-common = { workspace = true }
torch = { index = "pytorch-cu130" }

[tool.hatch.build.targets.wheel]
packages = ["src/adsmod_ml"]

[tool.pytest.ini_options]
pythonpath = ["src", "../common/src"]
cache_dir = "../../tests/cache/pytest"

[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"
